[package]
name = "actix-web-ult"
version = "0.1.0"
authors = ["Nikolay Koshkin <koshkin.kna@ya.ru>"]

[lib]
name = "actix_web_ult"
path = "src/lib.rs"

[dependencies]
actix-web = "0.6"
tera = "0.11"


